baseURL = 'https://chinjo.top/'
languageCode = 'en-us'
title = '竹青鱼'
theme="archie"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "qinjo"

paginate=5 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	description = '探索技术的极限，我将会带你见识建站、设计、技术、博客、资源、前端等不同类型的元素。'
	subtitle = '大器免成'
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://qinjo.github.io"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/chinjo425/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4