baseURL = 'https://chinjo.top/'
languageCode = 'en-us'
title = 'Hardy Blog'
theme="archie"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "qinjo"

paginate=5 # articles per page

[params]
	mode="toggle" # color-mode â†’ light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	description = 'æ¢ç´¢æŠ€æœ¯çš„æé™ï¼Œæˆ‘å°†ä¼šå¸¦ä½ è§è¯†å»ºç«™ã€è®¾è®¡ã€æŠ€æœ¯ã€åšå®¢ã€èµ„æºã€å‰ç«¯ç­‰ä¸åŒç±»å‹çš„å…ƒç´ ã€‚'
	subtitle = "å¤§æ™ºè‹¥æ„šğŸ« "
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://qinjo.github.io"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/chinjo425/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4